"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

export default function PasswordResetPage(){
  const [token,setToken]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>setToken(new URLSearchParams(window.location.search).get("token")||""),0);return()=>window.clearTimeout(timer)},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");setMessage("");try{if(token&&password!==confirm)throw new Error("Passwords match nahi karte.");const response=await fetch(token?"/api/auth/password/reset":"/api/auth/password/forgot",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(token?{token,password}:{email})});const payload=await response.json();if(!response.ok)throw new Error(payload.message||payload.error);setMessage(payload.message||"Request accepted.");}catch(reason){setError(reason instanceof Error?reason.message:"Request failed")}finally{setBusy(false)}};
  return <main style={{background:"radial-gradient(circle at 50% 0,rgba(239,179,79,.14),transparent 35%),#080604",color:"#f5ecdd",display:"grid",minHeight:"100vh",placeItems:"center",padding:20}}><section style={{background:"linear-gradient(145deg,#1a1209,#090704)",border:"1px solid rgba(239,179,79,.25)",borderRadius:20,maxWidth:520,padding:"35px 30px",width:"100%"}}><Link href="/" style={{color:"#efb34f",fontSize:11,letterSpacing:".14em",textDecoration:"none"}}>✦ SHAZAN AI</Link><small style={{color:"#9f9587",display:"block",fontSize:8,letterSpacing:".18em",marginTop:28}}>{token?"SECURE RESET":"ACCOUNT RECOVERY"}</small><h1 style={{fontFamily:"Georgia,serif",fontSize:38,fontWeight:400,margin:"8px 0 10px"}}>{token?"Choose a new password.":"Reset your password."}</h1><p style={{color:"#9f9587",fontSize:11,lineHeight:1.6}}>{token?"12+ characters with uppercase, lowercase, number and symbol.":"Account exist karta hai toh 30-minute one-time link email hoga."}</p><form onSubmit={submit}>{token?<><label style={{display:"block",fontSize:9,marginTop:20}}>New password<input type="password" value={password} onChange={(event)=>setPassword(event.target.value)} minLength={12} required style={{background:"#070503",border:"1px solid rgba(239,179,79,.22)",borderRadius:9,color:"#f5ecdd",display:"block",marginTop:7,padding:13,width:"100%"}}/></label><label style={{display:"block",fontSize:9,marginTop:14}}>Confirm password<input type="password" value={confirm} onChange={(event)=>setConfirm(event.target.value)} minLength={12} required style={{background:"#070503",border:"1px solid rgba(239,179,79,.22)",borderRadius:9,color:"#f5ecdd",display:"block",marginTop:7,padding:13,width:"100%"}}/></label></>:<label style={{display:"block",fontSize:9,marginTop:20}}>Email address<input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} required style={{background:"#070503",border:"1px solid rgba(239,179,79,.22)",borderRadius:9,color:"#f5ecdd",display:"block",marginTop:7,padding:13,width:"100%"}}/></label>}{(error||message)&&<p style={{background:error?"#2b130d":"#10251a",border:`1px solid ${error?"rgba(255,125,92,.4)":"rgba(105,214,160,.35)"}`,color:error?"#ffb09d":"#91e6ba",fontSize:10,padding:11}}>{error||message}</p>}<button disabled={busy} style={{background:"linear-gradient(135deg,#ffe09b,#efb34f)",border:0,borderRadius:9,color:"#1b1207",fontWeight:700,marginTop:20,padding:14,width:"100%"}}>{busy?"Please wait…":token?"Update password":"Send reset link"}</button></form></section></main>
}
