import LegalPage from "../legal/LegalPage";

export const metadata = { title: "Privacy Policy · SHAZAN AI" };

export default function PrivacyPage() { return <LegalPage label="PRIVACY POLICY" title="Your work stays yours." summary="This policy explains what SHAZAN AI Workflow Studio collects, why it is needed, how it is protected and the choices available to account holders." sections={[
  { title: "Information we process", items: ["Account information such as name, email address, verification state and secure session identifiers.", "Projects, workflow graphs, prompts, uploaded files and generated assets that you choose to store.", "Credit ledger, job status, provider request identifiers, security events and limited diagnostic metadata.", "Payment data is not collected during the current public beta because payments are server-disabled."] },
  { title: "How we use information", paragraphs: ["We process information to authenticate accounts, save projects, execute requested workflows, enforce credits, prevent abuse, provide support and keep the service secure. We do not sell personal information or use private projects to advertise to you."] },
  { title: "Processors and transfers", paragraphs: ["Cloudflare provides application, database, queue and object-storage infrastructure. Resend provides transactional email when enabled, Google provides optional OAuth, and an enabled AI provider receives only the workflow data required for the generation you request. Provider access is controlled server-side."] },
  { title: "Retention and deletion", paragraphs: ["Project and asset data is retained while your account is active or as needed to provide the service. Deleted assets are removed from private object storage and marked deleted in the database. Security, audit and ledger records may be retained where necessary for fraud prevention, accounting and legal obligations."] },
  { title: "Security and your rights", paragraphs: ["Passwords are stored as salted, peppered hashes; API keys are server-only; private assets require an authenticated ownership check. Depending on applicable law, you may request access, correction, export or deletion. The production legal contact must be activated and verified before public launch; until then the beta must remain access-controlled."] },
  { title: "Children and changes", paragraphs: ["The service is not directed to children under 13, or a higher local minimum age where required. Material policy changes will be dated on this page and communicated where legally required."] },
]} />; }
