import LegalPage from "../legal/LegalPage";

export const metadata = { title: "Terms of Service · SHAZAN AI" };

export default function TermsPage() { return <LegalPage label="TERMS OF SERVICE" title="Clear rules for creation." summary="These terms govern access to SHAZAN AI Workflow Studio. The current public beta provides a visibly labeled Mock Provider and does not sell credits or enable paid AI providers." sections={[
  { title: "Account eligibility", paragraphs: ["You must be legally able to enter this agreement and provide accurate account information. You are responsible for protecting your credentials and for activity under your account. Automated account creation, credential sharing and attempts to bypass rate limits are prohibited."] },
  { title: "Your content", paragraphs: ["You retain ownership of content you submit and outputs generated for you, subject to applicable law and third-party rights. You grant SHAZAN AI the limited rights needed to store, process and transmit that content to perform your requested workflows. You must have permission to upload and process the content."] },
  { title: "Demo service", paragraphs: ["Mock results are test artifacts, are always labeled Demo, and are not produced by a paid AI model. Demo credits have no cash value. Availability, formats and limits may change during beta. Paid providers, payments and community publishing remain server-disabled until separately announced."] },
  { title: "Availability and termination", paragraphs: ["The beta is provided on an as-available basis. We may suspend access to protect users, infrastructure or third parties, or for violation of these terms. You may stop using the service at any time. Sections that by nature should survive termination will continue to apply."] },
  { title: "Disclaimers and liability", paragraphs: ["To the maximum extent permitted by law, the beta is provided without warranties of uninterrupted availability, fitness or non-infringement. SHAZAN AI is not responsible for unlawful user content or decisions made solely from generated output. Nothing here excludes liability that cannot legally be excluded."] },
  { title: "Governing terms and contact", paragraphs: ["Mandatory consumer rights in your location continue to apply. Operator identity, governing jurisdiction and a monitored legal contact must be finalized before unrestricted public launch; until that gate is complete the service must not be represented as fully public-beta ready."] },
]} />; }
